### PR TITLE
Update ArgoCD installation docs

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

> /kind cleanup

**What does this PR do / why we need it**:
The bootstrap process generates the ArgoCD instance locally, which will be applied to create the resources on the cluster. Users don't have to create this instance manually
**Have you updated the necessary documentation?**

* [X] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by chetan-rns** [comment]
@bigkevmcd @wtam2018 I've updated the argocd installation docs and moved the section to the end of Day 1

**Review by wtam2018 — APPROVED** [review]

**Comment by wtam2018** [comment]
@chetan-rns /hold does not work yet.    Please convert it to Draft if you want to hold.

**Pull request merged**
